apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres 
spec:
  ingressClassName: nginx
  rules:
    - host: myargocd.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
            path: /
